<?php
/**
 * Magento
 *
 * @category    design
 * @package     chip_default
 * @copyright   Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 */
/* @var $this Mage_Reports_Block_Product_Viewed */
?>

<?php
    $_helper = $this->helper('catalog/output');
?>
<?php $_currency =  Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>

<section class="block-list block-viewed">
        <div class="slider-items ">

        <div class="container_16">
            <div class="grid_16">
                <div class="recently-viewed-wrapper">
                    <div class="section-heading">
                        <div class="grid_16 omega">
                            <h2><?php echo $this->__('Recently Viewed') ?></h2>
                            <div class="section-divider"></div>
                            <div class="navigation-buttons">
                                <?php if ($upsell_count >3): ?>
                                    <span class="button scroll-left"><i class="icon-angle-left"></i> <?php echo $this->__('previous') ?></span>
                                <?php endif; ?>
                                <?php if ($upsell_count >3): ?>
                                    <span class="button scroll-right"><?php echo $this->__('next') ?> <i class="icon-angle-right"></i></span>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

                    <div class="grid_11">

                        <div class="block-content iosSlider-recently">
                            <ul class="slider-items" id="recently-viewed-items">
                            <?php foreach ($_products as $_product): ?>
                                <li class="item">
                                    <div class="product-item">
                                        <?php
                                            $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                                            $_image = null;
                                            if (count($_gallery)) {
                                                foreach ($_gallery as $item)
                                                {
                                                    $_image = $item->getFile();
                                                }
                                            }
                                        ?>
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(300,null); ?>"
                                                 alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />

                                            <img class="hover-image"
                                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image',$_image)->keepFrame(false)->resize(300,null); ?>"
                                                 alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />

                                        </a>

                                        <h2 class="item fn product-name">
                                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                                        </h2>
                                        <span class="price"><?php echo $this->__('Price') ?>: <?php echo $_currency; ?><?php echo number_format($_product->getFinalPrice(),2); ?></span>
                                        <?php if($_product->getRatingSummary()): ?>
                                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php endif; ?>

                                        <?php if($_product->getRatingSummary()): ?>
                                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                        <?php endif; ?>
                                        <p class="short-description">
                                            <?php
                                            $_description = nl2br($_product->getShortDescription());
                                            if (strlen($_description) > 50) {
                                                echo substr($_description,0,50).' ...';
                                            } else {
                                                echo $_description;
                                            }
                                            ?>
                                        </p>

                                    </div>
                                </li>

                            <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <div class="grid_4 alpha ">
                        <div class="content-static-block">
                            <p><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('product_viewed')->toHtml(); ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php endif; ?>
