<?php
/**
 *
 * @category  design
 * @package   chip_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php echo $this->getChildHtml('product_viewed') ?>
<footer>
    <div class="footer-top">
        <div class="footer-container">
            <div class="googlemap-mobile">
                    <script type="text/javascript"
                        src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false">
                    </script>

                    <script>
                        var homeLatlng = new google.maps.LatLng(<?php echo Mage::getStoreConfig('chip/general/googlemap'); ?>);

                        function initialize() {
                            var mapProp = {
                                center: homeLatlng,
                                zoom: 7,
                                scrollwheel: false,
                                mapTypeId: google.maps.MapTypeId.ROADMAP
                            };

                            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
                            google.maps.event.addDomListener(window, 'resize', function() {
                                map.setCenter(homeLatlng);
                            });
                        }
                        google.maps.event.addDomListener(window, 'load', initialize);
                    </script>
                    <div class="googlemap-container">
                        <div class="company-informaion">
                            <div class="heading-company">
                                <span class="span-heading-icon"><span class="heading-icon"></span><?php echo $this->__('How to find?') ?></span>
                            </div>
                            <div class="company-info-content">
                                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_map_info')->toHtml(); ?>
                            </div>

                            <div class="triangle-wrapper"><div class="triangle"></div></div>
                        </div>

                        <div id="googleMap" style="width:auto;height:600px;"></div>
                    </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="wideimage" style="background: transparent url(<?php echo Mage::getBaseUrl('media') . '/magazento_chip/' . Mage::getStoreConfig('chip/wideimage/wide_image_footer'); ?>) 50% 50%  no-repeat; background-size: cover;">
            <div class="footer-container container_16">
                <div class="grid_1">
                    &nbsp;
                </div>
                <div class="grid_5 contacts-mobile">
                    <div class="logo-container ">
                        <a href="<?php echo $this->getUrl('') ?>"
                           title="<?php echo $this->getLogoAlt() ?>" class="logo">
                            <img class="logotype"
                                 src="<?php echo Mage::getBaseUrl('media') . '/magazento_chip/' . Mage::getStoreConfig('chip/general/logo'); ?>"
                                 alt="<?php echo $this->getLogoAlt() ?>"/>
                        </a>
                    </div>
                </div>
                <div class="grid_10 contacts-mobile">
                    <div class="footer-block small center section-heading">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_one')->toHtml(); ?>
                    </div>
                </div>


            </div>
        </div>
    </div>
</footer>