<?php
/**
 *
 * @category  design
 * @package   chip_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>



<section class="block block-facebook">
    <div class="block-content">
        <div class="fb-like-box" data-href="http://www.facebook.com/magazento"
             data-width="290" data-height="400" data-show-faces="true" data-stream="false"
             data-show-border="false" data-header="false"></div>
    </div>
</section>
