<?php
/**
 * 
 * @category  design
 * @package   chip_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>
<?php $collection = $this->getProductsCollection(); ?>
<?php if($collection->count()): ?>

<section class="widget-new-products">

    <div class="section-heading">
        <div class="grid_1 alpha ">
            &nbsp;
        </div>
        <div class="grid_14 alpha">
            <h2><?php echo $this->__('New Products') ?></h2>
            <div class="section-divider"></div>
            <div><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($this->getStaticBlock())->toHtml(); ?></div>
            <div class="navigation-buttons">
                <?php if ($collection->getSize() >3): ?>
                    <span class="button scroll-left"><i class="icon-angle-left"></i> <?php echo $this->__('previous') ?></span>
                <?php endif; ?>
                <?php if ($collection->getSize() >3): ?>
                    <span class="button scroll-right"><?php echo $this->__('next') ?> <i class="icon-angle-right"></i></span>
                <?php endif; ?>
            </div>
        </div>
        <div class="grid_1">
            &nbsp;
        </div>
    </div>


    <div class="grid_1 alpha">
        &nbsp;
    </div>
    <div class="grid_14 alpha">
        <div class="block-content iosSlider-newproducts">
            <ul class="slider-items">
                <?php foreach ($collection as $_product): ?>
                    <li class="item">
                        <div class="product-item">

                            <?php
                            $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                            $_image = null;
                            if (count($_gallery)) {
                                foreach ($_gallery as $item)
                                {
                                    $_image = $item->getFile();
                                }
                            }
                            ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->keepFrame(false)->resize(300,null); ?>"
                                     alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />

                                <img class="hover-image"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image',$_image)->keepFrame(false)->resize(300,null); ?>"
                                     alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />

                            </a>

                            <div class="promo-container">
                                <?php
                                $_promo = $this->helper('chip/data')->getPromoLabels($_product);
                                echo $_promo['sale'];
                                echo $_promo['new'];
                                ?>
                            </div>

                            <h2 class="item fn product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                            </h2>
                            <p class="short-description">
                                <?php
                                $_description = nl2br($_product->getShortDescription());
                                if (strlen($_description) > 120) {
                                    echo substr($_description,0,120).' ...';
                                } else {
                                    echo $_description;
                                }
                                ?>
                            </p>
                            <?php if($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                            <div class="price-box pricerange">
                                <div class="backgroundeffect">
                                    <span class="price"><?php echo $_currency; ?><?php echo number_format($_product->getFinalPrice(),2); ?></span>
                                </div>
                            </div>

                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <div class="grid_1 alpha">
        &nbsp;
    </div>
</section>
<?php endif ?>

