<?php
/**
 * 
 * @category  design
 * @package   chip_default
 * @author    Ivan Proskuryakov http://www.magazento.com <volgodark@gmail.com>
 * @copyright Copyright (C)2013 Magazento
 */
?>

<?php

$_currency =  Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
$helper = Mage::helper('cms');
$processor = $helper->getPageTemplateProcessor();
    
$slides = $this->getSlides();
if ($slides) {
?>
    <section class="slider homepage-slider">
        <div class="fullwidthbanner-container"  style="background:transparent !important;">

        <div class="fullwidthbanner"  style="background:transparent !important;">
                <ul>
                    <?php foreach ($slides as $item) {

                        $helper = Mage::helper('cms');
                        $processor = $helper->getPageTemplateProcessor();
                        $html = $processor->filter($item->getContent());

                        ?>
                        <!-- SLIDE UP -->
                        <li data-transition="slideup" data-slotamount="20" data-delay="11000">
                            <img src=""<?php echo $this->getSkinUrl('revolution_slider/images/slides/transparent.png')?>">
                            <?php echo $html; ?>
                        </li>
                    <?php } ?>
                </ul>
                <div class="tp-bannertimer tp-bottom"></div>
            </div>
        </div>

    </section>

<?php } ?>


<!--
##############################
 - ACTIVATE THE BANNER HERE -
##############################
-->

<script type="text/javascript">

    var tpj=jQuery;
    tpj.noConflict();

    tpj(document).ready(function() {

        if (tpj.fn.cssOriginal!=undefined)
            tpj.fn.css = tpj.fn.cssOriginal;

        tpj('.fullwidthbanner').revolution(
            {
                delay:9000,
                startheight:500,
                startwidth:960,

                hideThumbs:200,

                thumbWidth:100,							// Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                thumbHeight:50,
                thumbAmount:5,

                navigationType:"bullet",				// bullet, thumb, none
                navigationArrows:"solo",				// nexttobullets, solo (old name verticalcentered), none

                navigationStyle:"square",				// round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom


                navigationHAlign:"center",				// Vertical Align top,center,bottom
                navigationVAlign:"bottom",					// Horizontal Align left,center,right
                navigationHOffset:0,
                navigationVOffset:40,

                soloArrowLeftHalign:"left",
                soloArrowLeftValign:"center",
                soloArrowLeftHOffset:20,
                soloArrowLeftVOffset:0,

                soloArrowRightHalign:"right",
                soloArrowRightValign:"center",
                soloArrowRightHOffset:20,
                soloArrowRightVOffset:0,

                touchenabled:"on",						// Enable Swipe Function : on/off
                onHoverStop:"on",						// Stop Banner Timet at Hover on Slide on/off



                stopAtSlide:-1,							// Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
                stopAfterLoops:-1,						// Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic



                shadow:0,								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows  (No Shadow in Fullwidth Version !)
                fullWidth:"off"							// Turns On or Off the Fullwidth Image Centering in FullWidth Modus


            });

    });

</script>
